name: zernike
channels:
  - conda-forge
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - fonttools=4.53.0
  - freetype=2.12.1
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.45.3
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.3.1
  - llvm-openmp=18.1.6
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.0
  - pillow=10.3.0
  - pip=24.0
  - pthread-stubs=0.4
  - pyparsing=3.1.2
  - python=3.12.3
  - python-dateutil=2.9.0
  - python_abi=3.12
  - readline=8.2
  - setuptools=70.0.0
  - six=1.16.0
  - tk=8.6.13
  - tornado=6.4.1
  - tzdata=2024a
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.6
